function [lambda_b, u_global, info] = solve_dual_direct(subs, F, params)
% SOLVE_DUAL_DIRECT - Question 2.7: Assemble dual Schur complement to directly solve interface problems
%
% Principle (Dual / FETI approach):
% The dual method solves for the interface Lagrange multiplier lambda, rather than the interface displacement.
% The assembled dual interface problem is an augmented system:
% [ Sd G ] [ lambda ] [ -bd ]
% [ G^T 0 ] [ alpha ] = [ -e ]
% Where:
% Sd = A_ * Sd_diag * A_^T (Assembled dual Schur complement)
% bd = A_ * bd_diag (Dual right-hand side term)
% G = A_ * Rb_diag (Assembled rigid body mode)
% e = Rb_diag^T * bp_diag (Compatibility right-hand side term)
% After calculating lambda, the displacements of each substructure interface:
% u_b^(s) = Sp^(s)+ * (bp^(s) + lambda_b^(s)) + Rb^(s) * alpha^(s)

% Input:
% subs - Substructure array (generated by generate_substructures.m)
% F - Global load vector [Nn x 1]
% params - Parameter structure
%

% Output:
% lambda_b - Interface Lagrange multiplier [n_lambda x 1]
% u_global - Global displacement vector [Nn x 1]
% info - Solution information structure


    N_sub = params.N_sub;
    Nn    = params.Nn;
    E = params.E; S = params.S; h = params.h;
    k0 = E*S/h;

    fprintf('====================================\n');
    fprintf('Dual Schur Method - Direct Solution (Q2.7)\n');
    fprintf('====================================\n');

    
    % Determine the actual interface node (skeleton)
    % 1D: Interface node = Nodes shared by adjacent substructures (excluding global endpoints)
    
    true_intf_nodes = [];
    for s = 1:N_sub-1
        true_intf_nodes = [true_intf_nodes; s * params.Ne_sub + 1];
    end
    n_lambda = length(true_intf_nodes);

    fprintf('Interface Nodes (skeleton): '); disp(true_intf_nodes.');
    fprintf('Lagrange Number of multipliers: %d\n\n', n_lambda);


    % Local duality operator for each substructure

    for s = 1:N_sub
        nloc  = subs(s).nloc;
        K_sub = subs(s).K_sub;
        nodes_s = subs(s).node_ids;

        % Determine the local interface node index
        [~, loc_b_in_nodes] = ismember(true_intf_nodes, nodes_s);
        loc_b_idx = loc_b_in_nodes(loc_b_in_nodes > 0);
        nb_s = length(loc_b_idx);

        % Internal nodes = all non-interface nodes
        loc_i_idx = setdiff((1:nloc)', loc_b_idx);

        % Dirichlet BC elimination: the first node of substructure 1
        if s == 1
            loc_i_idx = setdiff(loc_i_idx, 1);  
        end

        % Extract submatrix
        Kbb = K_sub(loc_b_idx, loc_b_idx);
        Kbi = K_sub(loc_b_idx, loc_i_idx);
        Kii = K_sub(loc_i_idx, loc_i_idx);
        Kib = K_sub(loc_i_idx, loc_b_idx);

        % Local forces
        f_loc = F(nodes_s);
        fb = f_loc(loc_b_idx);
        fi = f_loc(loc_i_idx);

        % Original Schur supplement
        if isempty(loc_i_idx)
            Sp_s = Kbb;
            bp_s = fb;
        else
            Sp_s = Kbb - Kbi * (Kii \ Kib);
            bp_s = fb - Kbi * (Kii \ fi);
        end

        % The dual Schur complement is the pseudo-inverse of Sp, and the rigid body mode is the null space of Sp.
        tol_sv = 1e-10 * k0;
        if nb_s == 0
            Sd_s = []; Rb_s = []; bd_s = [];
        elseif nb_s == 1
            if abs(Sp_s) < tol_sv
                Sd_s = 0; Rb_s = 1; bd_s = 0;
            else
                Sd_s = 1/Sp_s; Rb_s = zeros(1,0); bd_s = Sd_s * bp_s;
            end
        else
            [~, Sig, V] = svd(Sp_s);
            sv = diag(Sig);
            n_zero = sum(sv < tol_sv);
            if n_zero == 0
                Sd_s = inv(Sp_s); Rb_s = zeros(nb_s, 0);
            else
                Sd_s = pinv(Sp_s, tol_sv);
                Rb_s = V(:, end-n_zero+1:end);
            end
            bd_s = Sd_s * bp_s;
        end

        % Stored in substructure
        subs(s).loc_b_idx_dual = loc_b_idx;
        subs(s).loc_i_idx_dual = loc_i_idx;
        subs(s).nb_dual   = nb_s;
        subs(s).Sp_dual   = Sp_s;
        subs(s).Sd_dual   = Sd_s;
        subs(s).Rb_dual   = Rb_s;
        subs(s).bp_dual   = bp_s;
        subs(s).bd_dual   = bd_s;
        subs(s).Kii_dual  = Kii;
        subs(s).Kib_dual  = Kib;
        subs(s).Kbi_dual  = Kbi;
        subs(s).fi_dual   = fi;

        fprintf('Substructure %d: nb=%d, float=%d, Rb column number=%d\n', ...
                s, nb_s, size(Rb_s,2)>0, size(Rb_s,2));
        if nb_s > 0 && nb_s <= 4
            fprintf('  Sp^(%d) = ', s); disp(Sp_s);
            fprintf('  bp^(%d) = [%s]\n', s, num2str(bp_s'));
        end
    end

    %Step 3: Dual Assembly Operator A_
  
    nb_total = 0;
    nb_offsets = zeros(N_sub+1, 1);
    for s = 1:N_sub
        nb_offsets(s) = nb_total;
        nb_total = nb_total + subs(s).nb_dual;
    end
    nb_offsets(N_sub+1) = nb_total;

    A_dual = zeros(n_lambda, nb_total);
    for s = 1:N_sub
        nb_s = subs(s).nb_dual;
        nodes_s = subs(s).node_ids;
        loc_b_global = nodes_s(subs(s).loc_b_idx_dual);

        for j = 1:nb_s
            gnode = loc_b_global(j);
            intf_idx = find(true_intf_nodes == gnode);
            if ~isempty(intf_idx)
                col = nb_offsets(s) + j;
                if s <= intf_idx       
                    A_dual(intf_idx, col) = 1;
                else                   
                    A_dual(intf_idx, col) = -1;
                end
            end
        end
    end

    fprintf('\nDual assembly operator A_ (%d x %d):\n', size(A_dual));
    disp(A_dual);


    %  Assemble dual interface problem
    
    % splicing block diagonal matrix
    Sd_diag = zeros(nb_total);
    bp_vec = zeros(nb_total, 1);
    bd_vec = zeros(nb_total, 1);
    n_rigid_total = 0;
    Rb_cells = cell(N_sub, 1);

    for s = 1:N_sub
        idx = nb_offsets(s)+1 : nb_offsets(s+1);
        Sd_diag(idx, idx) = subs(s).Sd_dual;
        bp_vec(idx) = subs(s).bp_dual;
        bd_vec(idx) = subs(s).bd_dual;
        Rb_cells{s} = subs(s).Rb_dual;
        n_rigid_total = n_rigid_total + size(subs(s).Rb_dual, 2);
    end
    Rb_diag = blkdiag(Rb_cells{:});

    % Assembly
    Sd = A_dual * Sd_diag * A_dual';
    bd = A_dual * bd_vec;
    G  = A_dual * Rb_diag;
    e_vec = Rb_diag' * bp_vec;

    fprintf('Sd (%dx%d):\n', size(Sd)); disp(Sd);
    fprintf('bd = [%s]\n', num2str(bd'));
    fprintf('G (%dx%d):\n', size(G)); disp(G);
    fprintf('e = [%s]\n', num2str(e_vec'));

    
    %  Direct solution of augmented systems
    
    if n_rigid_total > 0
        K_aug = [Sd, G; G', zeros(n_rigid_total)];
        rhs   = [-bd; -e_vec];
        sol   = K_aug \ rhs;
        lambda_b = sol(1:n_lambda);
        alpha_global = sol(n_lambda+1:end);
    else
        lambda_b = Sd \ (-bd);
        alpha_global = [];
    end

    fprintf('\nlambda_b = [%s]\n', num2str(lambda_b'));
    if ~isempty(alpha_global)
        fprintf('alpha    = [%s]\n', num2str(alpha_global'));
    end

    
    %  Restore displacement
   
    lambda_b_diag = A_dual' * lambda_b;
    u_global = zeros(Nn, 1);

    alpha_off = 0;
    for s = 1:N_sub
        nb_s = subs(s).nb_dual;
        nr_s = size(subs(s).Rb_dual, 2);
        nodes_s = subs(s).node_ids;

        idx = nb_offsets(s)+1 : nb_offsets(s+1);
        lam_s = lambda_b_diag(idx);

        if nr_s > 0
            alp_s = alpha_global(alpha_off+1 : alpha_off+nr_s);
            alpha_off = alpha_off + nr_s;
        else
            alp_s = [];
        end

        % Interface displacement
        ub_s = subs(s).Sd_dual * (subs(s).bp_dual + lam_s);
        if nr_s > 0
            ub_s = ub_s + subs(s).Rb_dual * alp_s;
        end

        % Internal displacement
        if ~isempty(subs(s).loc_i_idx_dual)
            ui_s = subs(s).Kii_dual \ (subs(s).fi_dual - subs(s).Kib_dual * ub_s);
        else
            ui_s = [];
        end

        % Global Assembly
        loc_b_global = nodes_s(subs(s).loc_b_idx_dual);
        for j = 1:nb_s
            u_global(loc_b_global(j)) = ub_s(j);
        end
        loc_i_global = nodes_s(subs(s).loc_i_idx_dual);
        for j = 1:length(ui_s)
            u_global(loc_i_global(j)) = ui_s(j);
        end

        fprintf('Substructure %d: u_b=[%s]\n', s, num2str(ub_s'));
    end

    u_global(1) = 0;  

    
    %  verify
    mesh_x = linspace(0, params.L, Nn)';
    u_exact = (params.Fd / (params.E * params.S)) * mesh_x;
    error_L2 = norm(u_global - u_exact) / norm(u_exact);

    kappa_Sd = cond(Sd);

    fprintf('\n====================================\n');
    fprintf('Verification results (Q2.7 Dual Direct Method)\n');
    fprintf('====================================\n');
    fprintf('u(L) Numerical solution  = %.12e m\n', u_global(end));
    fprintf('u(L) Analytical solution  = %.12e m\n', u_exact(end));
    fprintf('L2 relative error  = %.6e\n', error_L2);
    fprintf('kappa(Sd)    = %.6e\n', kappa_Sd);
    fprintf('====================================\n\n');

    %% Output info
    info.Sd        = Sd;
    info.bd        = bd;
    info.G         = G;
    info.e         = e_vec;
    info.alpha     = alpha_global;
    info.kappa_Sd  = kappa_Sd;
    info.error_L2  = error_L2;
    info.u_exact   = u_exact;
    info.n_lambda  = n_lambda;
    info.n_rigid   = n_rigid_total;
    info.A_dual    = A_dual;
    info.subs_updated = subs;
    info.nb_offsets   = nb_offsets;
    info.true_intf_nodes = true_intf_nodes;

end
