function [u_interface, u_global, info] = solve_schur_direct(subs, F, params)
% SOLVE_SCHUR_DIRECT - Question 2.1: Assemble the Global Primal Schur Complement and Solve the Interface Problem Directly
%
% Input:
% subs - Array of substructures (generated by generate_substructures.m)
% F - Global load vector [Nn x 1]
% params - Parameter structure (generated by config_params.m)
%
% Output:
% u_interface - Interface displacement vector (interface DOF only) [n_interface x 1]
% u_global - Global displacement vector [Nn x 1]
% info - Solution information structure
% .n_interface - Number of interface degrees of freedom
% .kappa_Sp - Number of conditions for the assembled Schur Complement
% .error_L2 - L2 relative error with the analytical solution
%


% Collect the DOF numbers of all substructure interfaces, remove duplicates, and sort them.
all_interface_dofs = [];
for s = 1:params.N_sub
    all_interface_dofs = [all_interface_dofs; subs(s).interface_dofs];
end
all_interface_dofs = unique(all_interface_dofs);  
n_interface = length(all_interface_dofs);



Sp = zeros(n_interface, n_interface);
for s = 1:params.N_sub
    % Find the indices of the two interface DOFs of this substructure in the global interface vector.
    [~, idx] = ismember(subs(s).interface_dofs, all_interface_dofs);
    %  Sp(idx, idx) += S_sub^(s)
    Sp(idx, idx) = Sp(idx, idx) + subs(s).S_sub;
end

fprintf('\nGlobal Schur complement matrix Sp (%dx%d):\n', n_interface, n_interface);


%   Assembly interface load vector f_Γ

f_interface = zeros(n_interface, 1);

for s = 1:params.N_sub
    nloc      = subs(s).nloc;
    K_sub     = subs(s).K_sub;

    % Local subscripts: Boundary nodes are the first and last ones.
    idx_b = [1; nloc];               % Local boundary subscript
    idx_i = (2:nloc-1)';             % Local internal subscript

    % Extract the local loads of this substructure from the global load vector.
    f_loc = F(subs(s).node_ids);     % [nloc x 1]

    f_b = f_loc(idx_b);              % Boundary load components

    if isempty(idx_i)
        f_contrib = f_b;
    else
        K_bb = K_sub(idx_b, idx_b);
        K_bi = K_sub(idx_b, idx_i);
        K_ii = K_sub(idx_i, idx_i);
        f_i  = f_loc(idx_i);
        f_contrib = f_b - K_bi * (K_ii \ f_i);
    end

    % Accumulated to global interface load
    [~, idx] = ismember(subs(s).interface_dofs, all_interface_dofs);
    f_interface(idx) = f_interface(idx) + f_contrib;
end

% Apply displacement boundary conditions (DOF 1 is fixed at 0, elimination method)
% DOF 1 is global number 1, i.e., the fixed left end of the rod.

[~, fixed_idx] = ismember(1, all_interface_dofs);  % find the dof in the vector of surface

if fixed_idx > 0
    Sp(fixed_idx, :) = 0;
    Sp(:, fixed_idx) = 0;
    Sp(fixed_idx, fixed_idx) = 1;
    f_interface(fixed_idx) = 0;
end

u_interface = Sp \ f_interface;
fprintf('  u_Γ = '); disp(u_interface.');


%  Back-substitution to restore the displacements of the internal degrees of freedom of each substructure

u_global = zeros(params.Nn, 1);

% First, write the interface displacement to the global displacement.
for k = 1:n_interface
    u_global(all_interface_dofs(k)) = u_interface(k);
end

% Then restore the internal displacement of each substructure.
for s = 1:params.N_sub
    nloc  = subs(s).nloc;
    K_sub = subs(s).K_sub;

    idx_b = [1; nloc];
    idx_i = (2:nloc-1)';

    if isempty(idx_i)
        continue;  
    end

    u_b = u_global(subs(s).interface_dofs);  % [2 x 1]

    f_i = F(subs(s).internal_dofs);          

    K_ii = K_sub(idx_i, idx_i);
    K_ib = K_sub(idx_i, idx_b);

    u_i = K_ii \ (f_i - K_ib * u_b);
    u_global(subs(s).internal_dofs) = u_i;
end

u_global(1) = 0;


%  Verification by comparison with analytical solution

mesh_x = linspace(0, params.L, params.Nn)';
u_exact = (params.Fd / (params.E * params.S)) * mesh_x;

error_L2 = norm(u_global - u_exact) / norm(u_exact);

% Calculating the condition number after removing the fixed DOF
if fixed_idx > 0
    free_idx = setdiff(1:n_interface, fixed_idx);
    Sp_free  = Sp(free_idx, free_idx);
else
    Sp_free = Sp;
end
kappa_Sp = cond(Sp_free);


info.n_interface = n_interface;
info.kappa_Sp    = kappa_Sp;
info.error_L2    = error_L2;
info.u_exact     = u_exact;
info.Sp          = Sp;              

end